---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pull-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pull-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        password: "{{ .FLUX_GITHUB_TOKEN }}"
        username: "git"
  dataFrom:
    - extract:
        key: flux
