---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discord-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        address: "{{ .DISCORD_FLUXCD_WEBHOOK }}"
  dataFrom:
    - extract:
        key: discord
