---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plausible
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plausible-secret
    creationPolicy: Owner
    template:
      data:
        CLICKHOUSE_DATABASE_URL: "http://chi-clickhouse-clickhouse-0-0.databases.svc.cluster.local:8123/plausible"
        DATABASE_URL: "postgres://{{ .PLAUSIBLE_POSTGRES_USER }}:{{ .PLAUSIBLE_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local/plausible"
        INIT_POSTGRES_DBNAME: plausible
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .PLAUSIBLE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PLAUSIBLE_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
  dataFrom:
    - extract:
        key: cloudnative-pg-superuser
    - extract:
        key: plausible
