---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cihub
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      autobrr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: getcihub/cihub
              tag: v0.1.0@sha256:d343957d0f4fb2f2d9774ef1a75b6498b5827cfc9de4cc4fd505fe8b8b7310ca
            env:
              CIHUB_CLICKHOUSE_DATABASE: plausible
            envFrom:
              - secretRef:
                  name: cihub-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    persistence:
      tmp:
        type: emptyDir
    ingress:
      app:
        className: external
        hosts:
          - host: cihub.nlecoy.fr
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    service:
      app:
        ports:
          http:
            port: 8080
