---
grafanaDashboard:
  enabled: true
serviceMonitor:
  enabled: true
spegel:
  containerdSock: /run/k3s/containerd/containerd.sock
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
service:
  registry:
    hostPort: 29999
