---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: clickhouse-volume
      podTemplate: clickhouse-server
  configuration:
    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      plausible/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-credentials
            key: plausible-password
      plausible/allow_databases/database:
        - "plausible"
  templates:
    podTemplates:
      - name: clickhouse-server
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:25.4
    volumeClaimTemplates:
      - name: clickhouse-volume
        spec:
          storageClass: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
