---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: clickhouse-volume
      podTemplate: clickhouse-server
  configuration:
    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      cihub/password:
        valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: cihub-password
        # to allow access outside from kubernetes
        cihub/networks/ip:
          - 0.0.0.0/0
        cihub/allow_databases/database:
          - cihub
          - system
      plausible/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-credentials
            key: plausible-password
      # to allow access outside from kubernetes
      plausible/networks/ip:
        - 0.0.0.0/0
      plausible/allow_databases/database:
        - plausible
        - system
  templates:
    podTemplates:
      - name: clickhouse-server
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:25.5
    volumeClaimTemplates:
      - name: clickhouse-volume
        spec:
          storageClass: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
