---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: clickhouse-credentials
    creationPolicy: Owner
    template:
      data:
        plausible-password: "{{ .PLAUSIBLE_CLICKHOUSE_PASS }}"
  dataFrom:
    - extract:
        key: plausible
