---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ovh-dns-api-credentials
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        OVH_APPLICATION_KEY: "{{ .OVH_APPLICATION_KEY }}"
        OVH_APPLICATION_SECRET: "{{ .OVH_APPLICATION_SECRET }}"
        OVH_CONSUMER_KEY: "{{ .OVH_CONSUMER_KEY }}"
  dataFrom:
    - extract:
        key: ovh
