---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ingress-nginx
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      allowSnippetAnnotations: true
      kind: DaemonSet
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      ingressClassResource:
        default: true
