---
web:
  port: ${GATUS_WEB_PORT}

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/37115765
  link: https://github.com/nlecoy
  buttons:
    - name: Github
      link: https://github.com/nlecoy
    - name: Homelab
      link: https://github.com/nlecoy/home-ops

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.nlecoy.fr
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
