---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: shelfmark-secret
    template:
      data:
        PROWLARR_ENABLED: "true"
        PROWLARR_URL: "prowlarr.default.svc.cluster.local"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
    - extract:
        key: prowlarr
