---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    prometheusRules:
      enabled: false
    serviceMonitor:
      enabled: true
      relabelings:
        - action: labeldrop
          regex: (pod)
