---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oauth2-proxy-secrets
    deletionPolicy: "Delete"
    template:
      data:
        cookie-secret: "{{ .OAUTH2_PROXY_COOKIE_SECRET }}"
        client-id: "{{ .OAUTH2_PROXY_CLIENT_ID }}"
        client-secret: "{{ .OAUTH2_PROXY_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: oauth2-proxy
