---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ['alertname', 'job']
    groupInterval: 5m
    groupWait: 30s
    receiver: 'discord'
    repeatInterval: 12h
    routes:
      - receiver: 'null'
        matchers:
          - name: alertname
            value: InfoInhibitor|Watchdog|CPUThrottlingHigh|KubeAggregatedAPIDown|KubeControllerManagerDown|KubeSchedulerDown
            matchType: =~
      - receiver: 'discord'
        matchers:
          - name: severity
            value: critical|warning
            matchType: =~
        continue: true
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: "discord"
      discordConfigs:
        - apiURL:
            key: discord-webhook-url
            name: alertmanager-secret
          title: >-
            {{ .GroupLabels.alertname }} - {{ .GroupLabels.namespace }}
            {{- if ne .CommonLabels.severity "" }} ({{ .CommonLabels.severity}}){{- end }}
            ({{ .GroupLabels.cluster }})
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
          message: |-
            {{- $root := . }}
            {{- $rm := stringSlice "instance" "kubernetes_node" "endpoint" "prometheus" "service" "cluster" "container" "job" "severity" }}
            {{- $common := ( ( .CommonLabels.Remove $root.GroupLabels.Names ).Remove $rm ) }}
            {{- if gt (len $common.SortedPairs) 0 }}
            ## Common Labels
            {{- range $common.SortedPairs }}
            > {{ .Name }}: `{{ .Value }}`
            {{- end }}
            {{- end }}
            ## Alerts
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
            - **{{ .Annotations.description }}** [{{ .Fingerprint }}]({{ .GeneratorURL }})
              {{- else if ne .Annotations.summary "" }}
            - **{{ .Annotations.summary }}** [{{ .Fingerprint }}]({{ .GeneratorURL }})
              {{- else if ne .Annotations.message "" }}
            - **{{ .Annotations.message }}** [{{ .Fingerprint }}]({{ .GeneratorURL }})
              {{- else }}
            - **Alert description not available** [{{ .Fingerprint }}]({{ .GeneratorURL }})
              {{- end }}
              {{- $uniq := ( ( .Labels.Remove $root.GroupLabels.Names ).Remove $root.CommonLabels.Names ) }}
              {{- if gt (len $uniq.SortedPairs) 0 }}
                {{- range $uniq.SortedPairs }}
            > {{ .Name }}: `{{ .Value }}`
                {{- end }}
              {{- end }}
            {{- end }}
