---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        discord-webhook-url: "{{ .DISCORD_ALERT_MANAGER_WEBHOOK }}"
  dataFrom:
    - extract:
        key: discord
