---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - ocirepository.yaml
  - helmrelease.yaml
  - prometheusrule.yaml
configMapGenerator:
  - name: alertmanager
    files:
      - config/alertmanagerconfig.yml
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
