---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      immich:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.0.3@sha256:c716dc20f957aafd89fa9d284a2ec63e25c9e2d8d8e87c6197d540a3dce237db
            env:
              DISABLE_REVERSE_GEOCODING: "true"
              ENABLE_MAPBOX: "false"
              IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
              LOG_LEVEL: verbose
              REDIS_DBINDEX: "1"
              REDIS_HOSTNAME: "dragonfly.databases.svc.cluster.local"
              REDIS_PORT: "6379"
              TZ: Europe/Paris
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4Gi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.0.3@sha256:d76fe88b69282c09a97eac4f82dafa82cfd77bce274bc742591cde974f87dacb
            env:
              MACHINE_LEARNING_CACHE_FOLDER: /cache
              MPLCONFIGDIR: /cache/matplotlib
              TZ: Europe/Paris
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: immich
        ports:
          http:
            port: &port 2283
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nlecoy.fr"
          - "photos.nlecoy.fr"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        type: nfs
        server: nas.internal
        path: /var/nfs/shared/photos
        globalMounts:
          - path: /usr/src/app/upload
      initdb:
        type: configMap
        name: immich-initdb
        advancedMounts:
          immich:
            init-db:
              - path: /initdb
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: openebs-hostpath
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
